### PR TITLE
development for revision 0.2

### PR DESCRIPTION
**Pull request by generationmake**
fix all known issues.

### CODE REVIEW

**Comment by aentinger** [comment]
Something is going on here =) ping @generationmake :coffee: :wave:

**Comment by generationmake** [comment]
@aentinger 
let me check this data so that we can make a clear cut and release 0.2 before we proceed with this board.

**Comment by generationmake** [comment]
Hi @aentinger 
I reviewed and updated the design. 
Please review.
From my side this revision is finished and able to merge. For future designs we proceed with new issues and a new revision.

**Review by aentinger — APPROVED** [review]
There's no pull-up on MISO, although its mentioned [here](https://github.com/107-systems/l3xz-leg-ctrl-hardware/issues/5#issuecomment-1140241926). Not sure if we really need it though :shrug: .

**Comment by generationmake** [comment]
@aentinger 
R17 on page 1 is our pull up resistor.

**Pull request merged**
